markdown: kramdown
permalink: /:year/:month/:day/:title/
url: http://jerkwin.github.io
author: Jerkwin
highlighter: rouge
safe: true
auto: true
future: true
paginate: 25
kramdown:
    toc_levels: 1..3
