markdown: kramdown
permalink: /:year/:month/:day/:title/
relative_permalinks: true
url: http://jerkwin.github.io
author: Jerkwin
pygments: true
safe: true
paginate: 25
auto: true
future: true
kramdown:
    toc_levels: 1..3
